### ISSUE TITLE
Clarify persistence guarantees (fault tolerance)

### ISSUE THREAD

**Issue by dumblob** [Terark/terark-db#11]
I've walked through the benchmarks and asked me one question - how is this DB fault tolerant? Does it use just `mmap` with populate? Concurrent writes to mmaped space do not provide any guarantees. And how about long writes (e.g. when the data to be written are huge - hundreds of MB)?

**Comment by rockeet** [comment]
We are using wiredtiger as writable segment(for now), new data goes in wiredtiger, then compressed to `dfadb` when the segment size reaches a threshold(default 3GB).
So the persistence guarantees are same as wiredtiger

**Comment by dumblob** [comment]
Thanks.
