### ISSUE TITLE
ZipIntStore::zipValues suggestion

### ISSUE THREAD

**Issue by v3rd1shax** [Terark/terark-db#5]
terak::db::ZipIntStore::zipValues takes a const void\* argument, and later then static cast it to const Int*. So maybe we can just modify the signature a little bit for better readability.
Before:

```
template<class Int>
void ZipIntStore::zipValues(const void* , size_t)
```

After:

```
template<class Int>
void ZipIntStore::zipValues(const Int* , size_t)
```

**Comment by rockeet** [comment]
Because parameter 'size' is measured in number of bytes, not in number of 'Int' elements, and 'Int' could be several different type of integers.  If param 'data' is type of 'Int*', the 'size' may be misunderstood as 'number of Int elements', and it needs type coerce at every calling place.
