### ISSUE TITLE
it's hard to install dependencies

### ISSUE THREAD

**Issue by 6api** [Terark/terark-db#8]
i spend all the day to try install them on debian wheezy & jessie,  but failed
i saw your offical website said in 0.13.9 have resolved this problem
but where is it?
thx

**Comment by royguo** [comment]
@6api We're sorry we didn't make it clear, we were going to disable Github release days ago. Now you can use the script below to help you download TerarkDB : 

```
sudo wget https://raw.githubusercontent.com/Terark/terark-db/master/online_install.py && (python online_install.py; rm online_install.py)
```

If the script can't find a package fit for your OS, please use the Download link directly on [TerarkDB webpage](http://terark.com/zh/products/terark-db)
