### ISSUE TITLE
Any plans to make `dfadb` open source?

### ISSUE THREAD

**Issue by dumblob** [Terark/terark-db#9]
Are there any plans to publish sources of `dfadb` core under some some permissive license (e.g. MIT)? If yes, what is the ETA?

I'm asking, because I'm working on a mid-size fully open-source project, which would leverage the compelling features of terark db, but only in case it's fully open source.

**Comment by rockeet** [comment]
Yes, dfadb core will be open sourced in the near future, but we can not give an ETA.
